const properties = [
  {
    id: 1,
    title: "Small Family Flat",
    price: "12,000",
    location: "Dhanmondi, Dhaka",
    bed: "2 Beds",
    bath: "1 Bath",
    size: "900 sqft",
    extra: "Balcony + Lift",
    badge: "Verified",
    
    images: ["images/OIP.webp", "images/singleroom1.webp","images/single3.webp","images/toilet.webp"],
    gender: "Male only",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Dhanmondi",
 summary: `The apartment includes all the basic facilities needed for a convenient lifestyle. 
The location is one of the biggest advantages. Being in Dhanmondi, everything you need is close by. 
The flat also includes a balcony and lift facility, adding extra comfort. 
Overall, this is a great option for male students or bachelors.`},
  {
    id: 2,
    title: "Luxury Apartment",
    price: "25,000",
    location: "Mirpur, Dhaka",
    bed: "3 Beds",
    bath: "2 Bath",
    size: "1500 sqft",
    extra: "Parking + Security",
    badge: "Featured",
    
    images: ["images/OIP.webp","images/01KNF50CAXDDNE1DHM6TZXK013.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Apartment",
    propertyType: "Flat",
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    summary: "Luxury apartment with parking and 24/7 security. Ideal for families."
  },
  {
    id: 3,
    title: "For Small Family",
    location: "Mirpur, Dhaka",
    price: "9,500",
    image: "images/OIP (1).webp",
    images: ["OIP (1).webp"],
    bed: "2 Beds",
    bath: "1 Bath",
    size: "650 sqft",
    extra: "Ground Floor",
    badge: "Verified",
    gender: "Family",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    summary: "Comfortable flat for small families. Ground floor, easy access."
  },
  {
    id: 4,
    title: "Student-Friendly Flat",
    location: "Nilkhet, Dhaka",
    price: "7,500",
    image: "university-boys-hostel.jpg",
    images: ["university-boys-hostel.jpg"],
    bed: "2 Beds",
    bath: "1 Bath",
    size: "600 sqft",
    extra: "WiFi Included",
    badge: "Student",
    gender: "Male only",
    availability: "Available",
    availableFrom: "February",
    category: "Hostel",
    propertyType: "Seat",
    division: "Dhaka",
    district: "Dhaka",
    area: "Nilkhet",
    summary: "Student-friendly flat near Nilkhet. WiFi included in rent. Near university area."
  },
  {
    id: 5,
    title: "Affordable Studio Flat",
    location: "Uttara, Dhaka",
    price: "6,800",
    image: "images/small-room1.jpg",
    images: ["images/small-room1.jpg"],
    bed: "Studio",
    bath: "1 Bath",
    size: "400 sqft",
    extra: "3rd Floor",
    badge: "New",
    gender: "Any",
    availability: "Available",
    availableFrom: "March",
    category: "Studio",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Uttara",
    summary: "Affordable studio flat in Uttara. Perfect for singles or couples. 3rd floor with natural light."
  },
  {
    id: 6,
    title: "Compact Bachelor Flat",
    location: "Mohammadpur, Dhaka",
    price: "9,000",
    image: "images/small-room2.jpg",
    images: ["images/small-room2.jpg"],
    bed: "1 Bed",
    bath: "1 Bath",
    size: "500 sqft",
    extra: "WiFi",
    badge: "Hot Deal",
    gender: "Male only",
    availability: "Available",
    availableFrom: "February",
    category: "Bachelor",
    propertyType: "Flat",
    division: "Dhaka",
    district: "Dhaka",
    area: "Mohammadpur",
    summary: "Compact bachelor flat with WiFi. Great location in Mohammadpur. Hot deal — limited time offer."
  },
  {
    id: 7,
    title: "New Flat",
    location: "Gulshan, Dhaka",
    price: "15,000",
    image: "images/download.jpeg",
    images: ["images/download.jpeg"],
    bed: "2 Bed",
    bath: "2 Bath",
    size: "900 sqft",
    extra: "Lift",
    badge: "Featured",
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulshan",
    summary: "Brand new flat in Gulshan with lift facility. Modern interior, great neighborhood."
  },
  {
    id: 8,
    title: "Modern Flat For Small-Family",
    location: "Gulshan, Dhaka",
    price: "15,000",
    image: "images/images (1).jpeg",
    images: ["images/images (1).jpeg"],
    bed: "2 Bed",
    bath: "2 Bath",
    size: "900 sqft",
    extra: "Kitchen",
    badge: "Featured",
    gender: "Family",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulshan",
    summary: "Modern flat with full kitchen setup. Ideal for small families in Gulshan."
  },
  {
    id: 9,
    title: "Sharing Student-Friendly Flat",
    location: "Gulistan, Dhaka",
    price: "15,000",
    image: "images/images.jpeg",
    images: ["images/images.jpeg"],
    bed: "2 Bed",
    bath: "2 Bath",
    size: "900 sqft",
    extra: "Lift",
    badge: "Student-Special",
    gender: "Male only",
    availability: "Available",
    availableFrom: "February",
    category: "Sharing",
    propertyType: "Flat",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulistan",
    summary: "Sharing flat for students. Lift facility available. Central location in Gulistan."
  },
  {
    id: 10,
    title: "Sharing Student-Friendly Flat",
    location: "Gulistan, Dhaka",
    price: "16,000",
    image: "images/a4-5.jpg",
    images: ["images/images.jpeg"],
    bed: "2 Bed",
    bath: "2 Bath",
    size: "900 sqft",
    extra: "Lift",
    badge: "Student-Special",
    gender: "Male only",
    availability: "Available",
    availableFrom: "March",
    category: "Sharing",
    propertyType: "Flat",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulistan",
    summary: "Sharing flat for students in Gulistan. Lift available. Close to educational institutions."
  },
  {
    id: 11,
    title: "Sharing Student-Friendly Flat",
    location: "Gulistan, Dhaka",
    price: "15,000",
    Image : "images/download (1).jpeg"
    images: ["images/download (1).jpeg"],
    bed: "2 Bed",
    bath: "2 Bath",
    size: "900 sqft",
    extra: "Lift",
    badge: "Student-Special",
    gender: "Any",
    availability: "Available",
    availableFrom: "February",
    category: "Sharing",
    propertyType: "Flat",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulistan",
    summary: "Affordable sharing flat for students. Lift facility. Good transport connections."
  },
  {
    id: 12,
    title: "Sharing Student-Friendly Flat",
    location: "Gulistan, Dhaka",
    price: "15,000",
    image:"images/download (2).jpeg",
    images: ["images/01KNF50AEW5M2V1H6D31FRFRN2.webp","images/download (1).jpeg"],
    bed: "2 Bed",
    bath: "2 Bath",
    size: "900 sqft",
    extra: "Lift",
    badge: "Student-Special",
    gender: "Female only",
    availability: "Available",
    availableFrom: "February",
    category: "Sharing",
    propertyType: "Flat",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulistan",
    summary: "Female-friendly sharing flat for students. Safe building with lift. Near Gulistan bus stop."
  },
  {
    id: 101,
    title: "Spacious  Family Apartment",
    price: "25,000",
    location: "Gulshan, Dhaka",
    bed: "3 Beds",
    bath: "3 Bath",
    size: "1350 sqft",
    extra: "Parking",
    badge: "Family Choice",
    image: "images/01KNF50C3WGVQHS0ZZ76D9AC0Y.webp",
    images: ["images/01KNF50C3WGVQHS0ZZ76D9AC0Y.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulshan",
    flatSize: "medium",
    summary: "Spacious 3BHK family apartment in Gulshan with parking facility. Perfect for growing families."
  },
  {
    id: 102,
    title: "Modern  with Study Room",
    price: "22,000",
    location: "Banani, Dhaka",
    bed: "2 Beds",
    bath: "2 Bath",
    size: "1100 sqft",
    extra: "Study Room",
    badge: "Featured",
    image: "images/01KNE5SSS03P9YNXDC0V9V7J7D.webp",
    images: ["images/01KNE5SSS03P9YNXDC0V9V7J7D.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Banani",
    flatSize: "medium",
    summary: "Modern 2BHK with dedicated study room in Banani. Great for professionals and small families."
  },
  {
    id: 103,
    title: " Private Terrace",
    price: "35,000",
    location: "Dhanmondi, Dhaka",
    bed: "3 Beds",
    bath: "3 Bath",
    size: "1500 sqft",
    extra: "Terrace",
    badge: "Premium",
    image: "images/01KNE5ST6D1DD1VNE0VHHJQJH8.webp",
    images: ["images/01KNE5ST6D1DD1VNE0VHHJQJH8.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Dhanmondi",
    flatSize: "medium",
    summary: "Luxury 3BHK with private terrace in Dhanmondi. Premium finishes throughout."
  },
  {
    id: 104,
    title: " Perfect for Couples",
    price: "18,000",
    location: "Uttara, Dhaka",
    bed: "2 Beds",
    bath: "2 Bath",
    size: "950 sqft",
    extra: "Modular Kitchen",
    badge: "Verified",
    image: "images/01KNE5STFMJPVJYWPY2Z18N6AP.webp",
    images: ["images/01KNE5STFMJPVJYWPY2Z18N6AP.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Uttara",
    flatSize: "medium",
    summary: "Cozy 2BHK with modular kitchen in Uttara. Perfect for couples or small families."
  },
  {
    id: 105,
    title: " with Servant Quarter",
    price: "28,000",
    location: "Bashundhara, Dhaka",
    bed: "3 Beds",
    bath: "3 Bath",
    size: "1600 sqft",
    extra: "Servant Room",
    badge: "Family Choice",
    image: "images/01KNEH2SVB7G8PZ0ES399H1RBM.webp",
    images: ["images/01KNEH2SVB7G8PZ0ES399H1RBM.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Bashundhara",
    flatSize: "medium",
    summary: "3BHK with servant quarter in Bashundhara. Ideal for large families."
  },
  {
    id: 106,
    title: " Duplex Apartment",
    price: "45,000",
    location: "Baridhara, Dhaka",
    bed: "4 Beds",
    bath: "4 Bath",
    size: "2000 sqft",
    extra: "Lift",
    badge: "Premium",
    image: "images/01KNEH2SNFC4JBMW95J23MZTGB.webp",
    images: ["images/01KNEH2SNFC4JBMW95J23MZTGB.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Duplex",
    division: "Dhaka",
    district: "Dhaka",
    area: "Baridhara",
    flatSize: "medium",
    summary: "4BHK duplex apartment in Baridhara with lift. Luxurious living in prime location."
  },
  {
    id: 107,
    title: " Corporate Housing",
    price: "30,000",
    location: "Mohakhali, Dhaka",
    bed: "3 Beds",
    bath: "3 Bath",
    size: "1400 sqft",
    extra: "WiFi",
    badge: "Verified",
    image: "images/01KNE5HS64JKF8BRZN2FP0X54J.webp",
    images: ["images/01KNE5HS64JKF8BRZN2FP0X54J.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Mohakhali",
    flatSize: "medium",
    summary: "3BHK corporate housing in Mohakhali with high-speed WiFi. Great for professionals."
  },
  {
    id: 108,
    title: " Garden View Apartment",
    price: "20,000",
    location: "Mirpur, Dhaka",
    bed: "2 Beds",
    bath: "2 Bath",
    size: "1050 sqft",
    extra: "Garden View",
    badge: "Verified",
    image: "images/01KNE0TY9KWC9CJ7WHH8WQFFD8.webp",
    images: ["images/01KNE0TY9KWC9CJ7WHH8WQFFD8.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    flatSize: "medium",
    summary: "2BHK garden view apartment in Mirpur. Natural light and beautiful garden scenery."
  },
  {
    id: 201,
    title: "Luxury  Penthouse",
    price: "80,000",
    location: "Gulshan, Dhaka",
    bed: "5 Beds",
    bath: "5 Bath",
    size: "3500 sqft",
    extra: "Swimming Pool",
    badge: "Premium",
    image:"images/01KNE0TY9KWC9CJ7WHH8WQFFD8.webp",
    images: ["images/01KNE0TY9KWC9CJ7WHH8WQFFD8.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Penthouse",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulshan",
    flatSize: "large",
    summary: "Luxury 5BHK penthouse in Gulshan with swimming pool and rooftop access."
  },
  {
    id: 202,
    title: "Spacious  Family Villa",
    price: "65,000",
    location: "Baridhara, Dhaka",
    bed: "4 Beds",
    bath: "4 Bath",
    size: "3000 sqft",
    extra: "Private Garden",
    badge: "Featured",
    image: "images/01KNE0TYFQJE5E12VSWAH18H65.webp",
    images: ["images/01KNE0TYFQJE5E12VSWAH18H65.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Villa",
    division: "Dhaka",
    district: "Dhaka",
    area: "Baridhara",
    flatSize: "large",
    summary: "Spacious 4BHK family villa in Baridhara with private garden."
  },
  {
    id: 203,
    title: " Duplex with Rooftop",
    price: "75,000",
    location: "Banani, Dhaka",
    bed: "5 Beds",
    bath: "5 Bath",
    size: "3200 sqft",
    extra: "Rooftop",
    badge: "Premium",
    image: "images/01KN9NEWHMYRREJVY17VBJE1S6.webp",
    images: ["images/01KN9NEWHMYRREJVY17VBJE1S6.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Duplex",
    division: "Dhaka",
    district: "Dhaka",
    area: "Banani",
    flatSize: "large",
    summary: "5BHK duplex with rooftop access in Banani. Perfect for large families."
  },
  {
    id: 204,
    title: " Corporate Residence",
    price: "55,000",
    location: "Dhanmondi, Dhaka",
    bed: "4 Beds",
    bath: "4 Bath",
    size: "2800 sqft",
    extra: "Gym",
    badge: "Featured",
    image:"images/01KN8X8XP55AXXVG7RH11DQX5D.webp",
    images: ["images/01KN8X8XP55AXXVG7RH11DQX5D.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Dhanmondi",
    flatSize: "large",
    summary: "4BHK corporate residence in Dhanmondi with gym facility."
  },
  {
    id: 205,
    title: " Royal Mansion",
    price: "1,20,000",
    location: "Gulshan, Dhaka",
    bed: "6 Beds",
    bath: "6 Bath",
    size: "5000 sqft",
    extra: "Home Theater",
    badge: "Royal",
    image: "images/1748704184_683b1bb857abc.jpeg",
    images: ["images/1748704184_683b1bb857abc.jpeg"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Mansion",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulshan",
    flatSize: "large",
    summary: "6BHK royal mansion in Gulshan with home theater and all luxury amenities."
  },
  {
    id: 206,
    title: " Lake View Apartment",
    price: "60,000",
    location: "Uttara, Dhaka",
    bed: "4 Beds",
    bath: "4 Bath",
    size: "2600 sqft",
    extra: "Lake View",
    badge: "Featured",
    image: "images/all property back.webp",
    images: ["images/all property back.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "February",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Uttara",
    flatSize: "large",
    summary: "4BHK lake view apartment in Uttara with scenic natural views."
  },
  {
    id: 207,
    title: " Smart Home",
    price: "90,000",
    location: "Bashundhara, Dhaka",
    bed: "5 Beds",
    bath: "5 Bath",
    size: "3800 sqft",
    extra: "Smart Home",
    badge: "Premium",
    image: "images/01KNF50CAXDDNE1DHM6TZXK013.webp",
    images: ["images/01KNF50CAXDDNE1DHM6TZXK013.webp"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Smart Home",
    division: "Dhaka",
    district: "Dhaka",
    area: "Bashundhara",
    flatSize: "large",
    summary: "5BHK fully automated smart home in Bashundhara with latest technology."
  },
  {
    id: 208,
    title: " Heritage Apartment",
    price: "50,000",
    location: "Mirpur, Dhaka",
    bed: "4 Beds",
    bath: "3 Bath",
    size: "2400 sqft",
    extra: "Community Hall",
    badge: "Verified",
    image: "images/tenant-singupback.jpg",
    images: ["images/tenant-singupback.jpg"],
    gender: "Family",
    availability: "Available",
    availableFrom: "March",
    category: "Flat",
    propertyType: "Apartment",
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    flatSize: "large",
    summary: "4BHK heritage apartment in Mirpur with community hall and spacious rooms."
  }

];